List all organizations
glific/glific-frontend pull request #1345
Opened 2021-04-28 10:15 UTC by shreesh1993

- Added organization list
- Now user can perform actions such as activate, approve and delete.
- There will be a confirmation message while deleting in-active/invalid organization.

closes  #1323

2021-04-29 15:37 UTC, DigneshGujarathi requested changes

2021-04-29 15:37 UTC, DigneshGujarathi commented on src/graphql/queries/Organization.ts
> +export const FILTER_ORGANIZATIONS = gql`
both are the same - FILTER_ORGANIZATIONS, FILTER_ORGANIZATIONS_NAME, please remove/reuse

2021-04-29 15:37 UTC, DigneshGujarathi commented on src/assets/images/icons/Organisation-1.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Are we using this?

2021-04-29 15:37 UTC, DigneshGujarathi commented on src/assets/images/icons/Organisation-2.svg
> +<?xml version="1.0" encoding="UTF-8"?>
are we using this?

2021-05-03 07:22 UTC, mdshamoon reviewed
Please change organization to organizations everywhere.

2021-05-03 07:22 UTC, mdshamoon commented on src/config/menu.ts
> +    roles: ['Manager', 'Admin'],
Just give rights for admin only.

2021-05-03 07:24 UTC, mdshamoon commented on src/context/role.ts
> +    if (user.name !== 'NGO Main Account') {
The user will be Saas Admin. Let's discuss and confirm in the call.

2021-05-05 05:21 UTC, mdshamoon approved these changes

2021-05-05 05:22 UTC, merged