Disabled editing triggers
glific/glific-frontend pull request #1727
Opened 2021-10-29 09:49 UTC by mdshamoon

## Summary

Disabled editing triggers

2021-11-02 23:04 UTC, kurund requested changes
@mdshamoon 

I can't add a new trigger. All the fields are disabled.

![Screenshot 2021-11-02 at 11 03 33 PM](https://user-images.githubusercontent.com/151481/139963719-fbfec70e-7536-4f51-9634-a090bd91174a.jpg)

2021-11-02 23:18 UTC, kurund commented
@mdshamoon 

I have pushed fixes to the above issue.

2021-11-08 12:04 UTC, mdshamoon commented
Tested and working fine now

2021-11-11 10:34 UTC, kurund approved these changes

2021-11-11 10:34 UTC, merged