Fixed UI for all forms in responsive view
glific/glific-frontend pull request #2110
Opened 2022-08-12 15:57 UTC by enigmaticmahesh

## Summary

Made forms responsive for mobile views.
PR for Issue #1582 
## Test Plan

2022-08-15 20:45 UTC, kurund requested changes

2022-08-15 20:45 UTC, kurund commented on src/containers/Search/Search.module.css
> +  .Form > div:nth-of-type(8), .Form > div:nth-of-type(9) {
This approach seems very fragile

2022-08-15 20:45 UTC, kurund commented on src/containers/SettingList/Organisation/Organisation.module.css
> +  .organization > div:nth-child(n + 2), .organization > div:first-child {
Let's discuss the approach. I feel it's better to have proper class selectors.

2022-08-18 05:21 UTC, enigmaticmahesh commented
@kurund I have made some changes as per the review. let me know for any changes if required

2022-08-21 21:42 UTC, kurund requested changes

2022-08-21 21:42 UTC, kurund commented on src/components/UI/Form/AutoComplete/AutoComplete.module.css
> +@media (max-width:768px) {
```suggestion
@media screen and (max-width: 768px) {
```

Can we please update media queries to include type in all places?

2022-08-21 21:42 UTC, kurund commented on src/components/UI/Form/Calendar/Calendar.module.css
> +@media (max-width:768px) {
Do you have formatting on Save on? There should be space after `:`

2022-08-21 21:42 UTC, kurund commented on src/containers/InteractiveMessage/InteractiveOptions/InteractiveOptions.module.css
> +  .ForMobile {
It's good to have className reflecting where it's used etc. So in this case may be chang it to `RadioGroup`

2022-08-21 21:42 UTC, kurund commented on src/containers/Trigger/Trigger.module.css
> +
Usually, VSCode automatically removes such extra spaces when you save the file if the format on saving is enabled.  Can you please check your editor settings?

2022-10-15 14:25 UTC, kurund approved these changes
made changes as per feedback.

2022-10-15 14:29 UTC, merged