momentjs/date-fns to dayjs
glific/glific-frontend pull request #2693
Opened 2024-01-04 18:48 UTC by akanshaaa19

## Summary

Migrated to dayjs from  date-fns / momentjs as now it's a recommended option by MUI. 
Check https://mui.com/x/react-date-pickers/#date-library
Datejs: https://day.js.org/
## Test Plan

2024-01-05 06:32 UTC, mdshamoon requested changes
Overall looks good.

Two things:
- We should remove date-fns also with dayjs as mentioned in the issue. There is still a date-fns adapter that is being used
- Remove moment and date-fns packages from package.json

2024-01-05 09:06 UTC, kurund commented on src/components/UI/Form/Calendar/Calendar.tsx
> +    if (date) {
@akanshaa19 Can you look at your editor's formatting?

2024-01-05 09:06 UTC, kurund commented on src/containers/Chat/ChatConversations/ChatConversations.tsx
> +
same as above.

2024-01-05 09:07 UTC, kurund commented on src/containers/List/List.tsx
> +  }
same as above

2024-01-07 13:53 UTC, kurund commented on src/common/constants.ts
> +  'https?://(www.)?[-a-zA-Z0-9@:%._+~#=]{2,256}.[a-z]{2,4}([-a-zA-Z0-9@:%_+.~#?&/=]*)';
was this an intentional change?

2024-01-07 13:54 UTC, kurund commented on src/common/constants.ts
> +export const is24HourWindowOver = (time: any) =>
extra space here too.

2024-01-08 03:21 UTC, akanshaaa19 commented on src/common/constants.ts
> +  'https?://(www.)?[-a-zA-Z0-9@:%._+~#=]{2,256}.[a-z]{2,4}([-a-zA-Z0-9@:%_+.~#?&/=]*)';
i guess prettier plugin did that

2024-01-10 07:42 UTC, mdshamoon commented on src/containers/SettingList/OrganizationFlows/OrganisationFlows.tsx
> +    setStartTime(dayjs(`${dayjs().format('YYYY-MM-DD')}T${data.startTime}`));
Just test this out once if its working fine.

2024-01-11 18:24 UTC, mdshamoon requested changes

2024-01-11 18:24 UTC, mdshamoon commented on src/components/UI/Form/DateTimePicker/DateTimePicker.tsx
> +  format = 'DD/MM/YYYY hh:mm a',
We should use the constant here.

2024-01-11 18:24 UTC, mdshamoon commented on src/mocks/Trigger.tsx
> +          endDate: dayjs('2021-03-13'),
This is a query mock. It represents the data that will be sent by the backend using a particular query. In this case backend will send back a date string only and not a dayjs object. Please update this.

2024-01-11 18:24 UTC, mdshamoon commented on src/mocks/Trigger.tsx
> +          startAt: dayjs('2021-02-28T20:00:22Z'),
Same here.

2024-01-11 18:24 UTC, mdshamoon commented on src/common/constants.ts
> +export const FULL_DATE_FORMAT_WITH_MONTH = 'DD MMM YYYY';
```suggestion
export const SHORT_DATE_FORMAT = 'DD/MM/YY';
export const LONG_DATE_FORMAT = 'DD/MM/YYYY';
export const ISO_DATE_FORMAT = 'YYYY-MM-DD';
export const DATE_FORMAT_WITH_MONTH = 'DD MMM YYYY';
```

2024-01-11 18:24 UTC, mdshamoon commented on src/common/constants.ts
> +export const DATE_TIME_FORMAT_WITH_AMPM2 = 'DD MMM YYYY hh:mm a';
```suggestion
export const SHORT_TIME_FORMAT = 'HH:mm';
export const LONG_TIME_FORMAT = 'HH:mm:ss';
export const EXTENDED_TIME_FORMAT = 'THH:mm:ss';
export const STANDARD_DATE_TIME_FORMAT = 'DD/MM/YYYY, HH:mm:ss';
export const SHORT_DATE_TIME_FORMAT_ = 'DD/MM/YYYY, HH:mm';
export const EXTENDED_DATE_TIME_FORMAT = 'MMMM DD, YYYY, [at] HH:mm:ss';
export const DATE_TIME_FORMAT_WITH_AMPM_SHORT = 'DD/MM/YYYY_hh:mmA';
export const DATE_TIME_FORMAT_WITH_AMPM_LONG = 'DD MMM YYYY hh:mm a';
```

2024-01-13 14:12 UTC, mdshamoon approved these changes

2024-01-13 14:13 UTC, merged