migration-from-draft-js
glific/glific-frontend pull request #2742
Opened 2024-02-06 05:54 UTC by akanshaaa19

## Summary

## Test Plan

2024-02-09 04:49 UTC, mdshamoon requested changes

2024-02-09 04:49 UTC, mdshamoon commented on package.json
>      "@mui/icons-material": "^5.15.6",
Remove draft js and plugins from package.json

2024-02-09 04:49 UTC, mdshamoon commented on src/common/RichEditor.tsx
> +};
If its directly returning the editor state I don't think we need this function.

2024-02-09 04:49 UTC, mdshamoon commented on src/components/UI/EmojiPicker/EmojiPicker.tsx
> +export const EmojiPicker = ({ displayStyle, onEmojiSelect }: EmojiPickerProps) => {
```suggestion
export const EmojiPicker = ({ displayStyle }: EmojiPickerProps) => {
```
Remove this if not needed. 
Also I am not sure if we should tightly couple editor with the picker. There could be a case where the emoji picker is needed without the editor. Let's discuss this once

2024-02-09 04:49 UTC, mdshamoon commented on src/components/UI/Form/EmojiInput/EmojiInput.tsx
> +  const lexicalChange = (editorState: any) => {
```suggestion
  const lexicalChange = (editorState: string) => {
```
Let's add types where we know

2024-02-09 04:49 UTC, mdshamoon commented on src/components/UI/Form/WhatsAppEditor/WhatsAppEditor.module.css
> +  /* padding: 4px 10px; */
Remove if not needed

2024-02-09 04:49 UTC, mdshamoon commented on src/containers/Chat/ChatMessages/ChatInput/ChatInput.tsx
> +              // disabled={(!attachmentAdded && !recordedAudio) || uploading}
Please check if this needs to commented out.

2024-02-09 04:49 UTC, mdshamoon commented on src/containers/InteractiveMessage/InteractiveMessage.helper.ts
> +      // .transform((_current, original) => original.getCurrentContent().getPlainText())
Remove of not needed. Please check other places as well

2024-02-15 07:43 UTC, mdshamoon commented
Testing feedbacks:

1. In templates page, the text moves out of the box if I type a long message
<img width="620" alt="image" src="https://github.com/glific/glific-frontend/assets/32592458/1f76208d-5f78-4327-a007-3ae64f30ff09">

2. Mentions plugin seems a bit buggy in interactive messages. Not able to select using keyboard arrows and enter button. Also it moves along with scroll
<img width="450" alt="image" src="https://github.com/glific/glific-frontend/assets/32592458/ab6c800b-23e3-4a96-ba88-72d869b77a90">

3. Pressing shift + enter should move to a new line and not send a message on chat screen
<img width="871" alt="image" src="https://github.com/glific/glific-frontend/assets/32592458/b279df36-a189-4c07-b6be-f60c40d12211">

2024-02-17 20:47 UTC, akanshaaa19 commented
@mdshamoon resolved these

2024-02-21 08:09 UTC, mdshamoon requested changes
Overall functionality wise it looks good. Some minor tweeks needed.

2024-02-21 08:09 UTC, mdshamoon commented on src/components/UI/Form/WhatsAppEditor/WhatsAppEditor.tsx
> +  }, []);
Check if we even need this. If not lets remove it.

2024-02-21 08:09 UTC, mdshamoon commented on src/components/UI/Form/WhatsAppEditor/WhatsAppEditor.tsx
> +        return text;
This is used in multiple places. Move this to utils and import everywhere.

2024-02-21 08:09 UTC, mdshamoon commented on src/components/UI/Form/WhatsAppEditor/WhatsAppEditor.tsx
> +        }
This part is also common and can be reused. Move this to utils and import here

2024-02-21 08:09 UTC, mdshamoon commented on src/components/UI/MessageDialog/MessageDialog.tsx
> +          handleHeightChange={() => {}}
Check if this is needed?

2024-02-21 08:09 UTC, mdshamoon commented on src/containers/Chat/ChatMessages/ChatInput/ChatInput.test.tsx
>        </MockedProvider>
This seems to be common in all the test cases. Create a function for this and reuse.
```suggestion
   const chatInput= (props) =>
        <LexicalComposer
          initialConfig={{
            namespace: 'chat-input',
            onError: (error: any) => console.log(error),
          }}
        >
          <ChatInput {...props} />
        </LexicalComposer>
      </MockedProvider>
```

2024-02-21 08:09 UTC, mdshamoon commented on src/containers/Chat/ChatMessages/ChatMessages.tsx
> +        style={{ height: `calc(100% - 215px ` }}
Any reason we increased the height?

2024-02-21 08:09 UTC, mdshamoon commented on src/containers/Template/Form/SpeedSend/SpeedSend.test.tsx
> +  },
Do we need this. I think we already imported it.

2024-02-26 05:46 UTC, mdshamoon approved these changes

2024-02-28 03:35 UTC, merged