Updated the error message in HSM templates
glific/glific-frontend pull request #2845
Opened 2024-04-09 08:09 UTC by akanshaaa19

Updated the error message for different sample messages in HSM templates
Target issue is #2740 

![image](https://github.com/glific/glific-frontend/assets/76031685/239b539f-a366-4847-91ac-64f52f21e789)

2024-04-09 08:11 UTC, akanshaaa19 commented
@KrishnaDwibhashi2 hey can you have a look at this, if the error message looks fine?

2024-04-15 02:08 UTC, kurund requested changes

2024-04-15 02:08 UTC, kurund commented on src/containers/Template/Form/Template.tsx
> +          'Message and sample look different. You have to replace variables eg. {{1}} with actual values enclosed in [ ] eg. Replace {{1}} with [Monica].',
Can you add translation support for these error messages?

2024-04-18 11:12 UTC, mdshamoon approved these changes

2024-04-18 11:12 UTC, merged