Feature: Terms and conditions UI
glific/glific-frontend pull request #2880
Opened 2024-04-29 14:09 UTC by akanshaaa19

2024-05-08 21:45 UTC, kurund commented
@akanshaaa19 

I have a few questions on code structure, it might be easier to discuss over the call.

2024-05-09 03:29 UTC, akanshaaa19 commented
> @akanshaaa19
> 
> I have a few questions on code structure, it might be easier to discuss over the call.

okay, let me know if we can connect today?

2024-05-15 19:06 UTC, kurund requested changes
Overall code looks good. Please check the comments. I have also pushed minor fixes.

2024-05-15 19:06 UTC, kurund commented on src/containers/Organization/Onboarding/Steps/OrgDetails.tsx
> +import axios from 'axios';
Can you please reorder the imports to include external packages first followed by internal ones.

2024-05-15 19:06 UTC, kurund commented on src/containers/Organization/Onboarding/Steps/PlatformDetails.tsx
> +      .required('Organisation Name is required.')
Can you please add localization for the messages?

2024-05-15 19:06 UTC, kurund commented on src/containers/Organization/Onboarding/Steps/SigningAuthority.tsx
> +      .required(t('Name is required.'))
please add localization for the messages.

2024-05-15 21:35 UTC, kurund commented
@akanshaaa19 

I have also cleaned the form and updated the labels. It would be good to deploy it on staging.

2024-05-20 23:14 UTC, kurund requested changes
Can we also make the Reach out form compact, it has lot of whitespace at bottom.

2024-05-20 23:21 UTC, kurund commented
@akanshaaa19 

I have also made a few changes to the landing page and shortcode logic. It would be good to deploy the same on staging.

2024-05-21 03:41 UTC, akanshaaa19 commented
> @akanshaaa19
> 
> I have also made a few changes to the landing page and shortcode logic. It would be good to deploy the same on staging.

made the require changes, its good to go now @kurund

2024-05-25 17:00 UTC, kurund commented
@KrishnaDwibhashi2 @akanshaaa19 

I thought about the names of the steps and made a few changes. Please let me know what you think.

<img width="369" alt="Screenshot 2024-05-25 at 17 55 50" src="https://github.com/glific/glific-frontend/assets/151481/7cad0598-501d-4015-b9a2-1baa8f331a38">

I was also wondering if we should change the step order.  Move Organization as the first step and Bot details to the second.

2024-05-27 09:10 UTC, KrishnaDwibhashi2 commented
@kurund 

I kind of feel it incomplete without the details suffix. Like the word "Billing" instead of "payment", but again having it as Billing details would make it complete for me (this is a very subjective opinion)

Initial design had org name first & then bot details. But as we won't be able to create entry at backend if the bot details are not asked in the first page, we changed the sequence.

2024-05-27 22:12 UTC, kurund commented
@KrishnaDwibhashi2 

Let's discuss and finalize this during our call.

2024-05-31 21:35 UTC, kurund approved these changes
Looks good.

2024-05-31 21:36 UTC, merged