Feature: Template flows
glific/glific-frontend pull request #2975
Opened 2024-07-11 06:49 UTC by akanshaaa19

2024-07-15 11:18 UTC, mdshamoon requested changes

2024-07-15 11:18 UTC, mdshamoon commented on src/containers/Form/FormLayout.tsx
> +                  if (additionalAction?.state === 'template') {
If possible can we make a generic way to update this and not hardcode template inside formlayout component

2024-07-15 11:18 UTC, mdshamoon commented on src/containers/Flow/FlowList/FlowList.test.tsx
> +  getFlowCountQuery(isActiveFilter),
At this point can you check why there are multiple calls being made to filter and count query and see if you can reduce them. If it seems to take more time, do it in a separate PR

2024-07-17 04:14 UTC, akanshaaa19 commented
> 1. Ideally view it should directly open the flow. What would opening the flow in edit mode achieve.
> 
> <img alt="Screenshot 2024-07-15 at 4 39 40 PM" width="251" src="https://private-user-images.githubusercontent.com/32592458/348683835-3efc2ea8-a890-4b43-a92e-992aca6a6dd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODk4NzcsIm5iZiI6MTcyMTE4OTU3NywicGF0aCI6Ii8zMjU5MjQ1OC8zNDg2ODM4MzUtM2VmYzJlYTgtYTg5MC00YjQzLWE5MmUtOTkyYWNhNmE2ZGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA0MTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMDdlOGZlNTA4ZWMwMjFhMDEyMWEzNDI4OTIzODMwYTc3OGY0NzQ4YmNhOGMyMzM1YTk0M2FjYmRkODZkOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UTqvLEK9FRbwFl70-55GM0jyyulSGbHgt_xXmtPGmoM">
> 2. Lets call the menu item templates since we are already inside flows.
> 
> <img alt="Screenshot 2024-07-15 at 4 38 33 PM" width="347" src="https://private-user-images.githubusercontent.com/32592458/348683886-a4a304e6-2f70-4a99-9db9-f2343f1db819.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODk4NzcsIm5iZiI6MTcyMTE4OTU3NywicGF0aCI6Ii8zMjU5MjQ1OC8zNDg2ODM4ODYtYTRhMzA0ZTYtMmY3MC00YTk5LTlkYjktZjIzNDNmMWRiODE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA0MTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMDNmYjZkNzMxMzg5NTg3OTNlOGU2YzE0YWNiY2VjMjJkNjUwYzBiMWU2ODg0NWQxZmIwYWVlYTBjN2E2ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JKCQHM717_yOqjhmWaIC7DJifUp84286m85PaifUNwE">

on view it we will show description about the template flow thats why it takes to edit page first

2024-07-23 04:56 UTC, mdshamoon reviewed
Please check failing unit and integration test cases. Otherwise looks good

2024-07-24 06:50 UTC, mdshamoon approved these changes

2024-07-24 06:50 UTC, merged