Enhancement/erp
glific/glific-frontend pull request #3127
Opened 2024-11-04 07:53 UTC by akanshaaa19

target issue is #3105

2024-11-12 23:54 UTC, kurund requested changes
@akanshaaa19 

We need better error handling. If someone tries to register and org does not exist the form fails silently. We should at least show some error.

2024-11-12 23:54 UTC, kurund commented on src/App.tsx
> +  axios
This seems wrong.

2024-11-13 04:43 UTC, akanshaaa19 commented on src/App.tsx
> +  axios
sorry, this was a mistake

2024-11-13 04:46 UTC, akanshaaa19 commented
> @akanshaaa19
> 
> 1. We need better error handling. If someone tries to register and org does not exist the form fails silently. We should at least show some helpful message.
> 2. Can you also fix failing unit tests?
> 3. I am also trying to register a new org: `Example NGO` and the backend is failing with an error. Note that `Example NGO` has been added to Frappe.
> 
> Let's discuss.

1. There is error handling for when org doesn't exist in erp.
<img width="658" alt="image" src="https://github.com/user-attachments/assets/eaa71dba-3e63-49d6-b44e-f180f369a235">
2. done
3. yes amisha is looking into that

2024-11-13 07:56 UTC, kurund commented
@akanshaaa19 

Can you update the message to: "Example organization not found". Please contact the Glific support team.

2024-11-13 10:31 UTC, akanshaaa19 commented
> @akanshaaa19
> 
> Can you update the message to: "Example organization not found". Please contact the Glific support team.

sure @AmishaBisht will be doing that from the BE

2024-11-15 10:45 UTC, AmishaBisht commented
> > @akanshaaa19
> > Can you update the message to: "Example organization not found". Please contact the Glific support team.
> 
> sure, @AmishaBisht will be doing that from the BE @kurund

done @akanshaaa19 @kurund

2024-11-17 19:57 UTC, kurund commented
@akanshaaa19 

1. In my opinion, we should change the below validation. 

<img width="1026" alt="Screenshot 2024-11-17 at 19 41 15" src="https://github.com/user-attachments/assets/7d27bf2f-76cd-45eb-862e-88658d121fd7">

Why is this necessary? If it's something to do with the backend then we can automatically do such conversion.  Let's chat.

2. Error on GST

<img width="1058" alt="Screenshot 2024-11-17 at 19 44 44" src="https://github.com/user-attachments/assets/9319576c-d04e-4d80-9111-8c1391fa55c2">

This just shows red without any message.

3. Incorrect field label

<img width="1096" alt="Screenshot 2024-11-17 at 19 46 49" src="https://github.com/user-attachments/assets/e2862f70-41bd-4b19-a493-13903749b123">

2024-11-17 20:00 UTC, kurund commented
@AmishaBisht 

> > > @akanshaaa19
> > > Can you update the message to: "Example organization not found". Please contact the Glific support team.
> > 
> > 
> > sure, @AmishaBisht will be doing that from the BE @kurund
> 
> done @akanshaaa19 @kurund

Looks like it's not done, we still have `Customer`


<img width="525" alt="Screenshot 2024-11-17 at 19 59 35" src="https://github.com/user-attachments/assets/152f45ba-d255-45e6-9bff-0409b89d4b0b">

2024-11-18 05:32 UTC, AmishaBisht commented
> @AmishaBisht
> 
> > > > @akanshaaa19
> > > > Can you update the message to: "Example organization not found". Please contact the Glific support team.
> > > 
> > > 
> > > sure, @AmishaBisht will be doing that from the BE @kurund
> > 
> > 
> > done @akanshaaa19 @kurund
> 
> Looks like it's not done, we still have `Customer`
> 
> <img alt="Screenshot 2024-11-17 at 19 59 35" width="525" src="https://private-user-images.githubusercontent.com/151481/386997195-152f45ba-d255-45e6-9bff-0409b89d4b0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDU4MDgsIm5iZiI6MTczMTkwNTUwOCwicGF0aCI6Ii8xNTE0ODEvMzg2OTk3MTk1LTE1MmY0NWJhLWQyNTUtNDVlNi05YmZmLTA0MDliODlkNGIwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwNDUxNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmI5Y2U4YjdhZjY3NDZmZjkyYzNlYTQ4YzAxYzA2MTY5NWE2MmQ2M2E2YTQ0ZGQxZTQ2ODgyMzhhYWRmMjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ph2RB434xOYUirpkmaWdJUsBdig490GFwrcSaRzYy3I">

@kurund the error message I'm receiving is directly from ERP, and I'm passing it along as-is.

2024-11-20 22:29 UTC, kurund approved these changes
Looks good.

Please note the dependency on https://github.com/glific/glific/pull/3893

2024-11-20 22:29 UTC, merged