Added warning if flow is not published
glific/glific-frontend pull request #3142
Opened 2024-11-25 05:26 UTC by akanshaaa19

target issue is #3115

2024-11-25 23:53 UTC, kurund requested changes
@akanshaaa19 

Tests are failing, can you please check

2024-12-10 22:54 UTC, kurund reviewed
@akanshaaa19 

I don't see any warning message. 

Steps that I followed.
- created new flow and published
- tried editing the above flow and remove some node and clicked on menu links it navigated to the same without any warning.

May be I am missing something. Lets discuss during our call.

2025-08-11 07:45 UTC, akanshaaa19 commented
closing because we are not picking this up right now

2025-08-11 07:45 UTC, closed without merging

2025-08-11 07:50 UTC, shijithkjayan commented
~~@akanshaaa19 Do we have to close this? Can't we keep it in the backlog and get to it when we get some time?~~

NVM, thought it was the issue that you are closing🤦