Added drop down icon for menu items that have sub menu items #3138
glific/glific-frontend pull request #3171
Opened 2024-12-15 17:32 UTC by Vimalnegi03

**Description-:**Added drop down icon for menu items that have sub menu items #3138 
![Screenshot_15-12-2024_19493_glific test](https://github.com/user-attachments/assets/7a4b235e-e65d-4019-8614-77702193f6f2)
![Screenshot_15-12-2024_194833_glific test](https://github.com/user-attachments/assets/3f433bd7-2f55-4887-9e9d-8030ef190a3f)

2024-12-15 21:00 UTC, kurund requested changes
@Vimalnegi03 

Thank you.

Icons are not aligned correctly.  It should not be dependent on the length of the menu.

2025-07-21 22:32 UTC, kurund commented
Hi @Vimalnegi03 

Just wondering if you are still interested in following up on this PR?

2025-07-22 13:06 UTC, Vimalnegi03 commented
Unfortunately, I’m unable to continue with this PR due to some personal reasons. I sincerely apologize for any inconvenience this may cause.

Thank you again for considering my contribution, and I hope to be able to collaborate in the future.

2025-09-24 09:12 UTC, akanshaaa19 commented
closing this PR due to inactivity

2025-09-24 09:12 UTC, closed without merging