Feature/add tags with autocomplete
glific/glific-frontend pull request #339
Opened 2020-08-19 11:59 UTC by rathorevaibhav

## Summary

Updated field in message tag assignment popup to have autocomplete field.

2020-08-19 15:21 UTC, kurund requested changes
@rathorevaibhav Existing groups should be preset in the autocomplete and not below. In the current form, we can't remove tags too.

![Screenshot 2020-08-19 at 8 49 30 PM](https://user-images.githubusercontent.com/151481/90654092-a10c5f80-e25d-11ea-8e35-9adf30bd7cc5.jpg)

2020-08-20 12:10 UTC, rathorevaibhav commented
@kurund ready for review again. Worked on the feedbacks

2020-08-20 18:18 UTC, kurund approved these changes
Looks good!

2020-08-20 18:18 UTC, merged

2020-08-23 19:13 UTC, kurund commented on src/containers/Chat/ChatMessages/ChatMessages.tsx
> +import AutoComplete from '@material-ui/lab/Autocomplete';
@rathorevaibhav Can you use our abstracted AutoComplete.