Added multi select functionality in search tag
glific/glific-frontend pull request #455
Opened 2020-09-10 15:27 UTC by rathorevaibhav

## Summary

Added multi-select functionality in add tags to message dialog box.

## Test Plan

Added

2020-09-10 18:11 UTC, kurund requested changes
@rathorevaibhav I think we should switch this to use abstracted autocomplete so that we are consistent with the UI.

![Screenshot 2020-09-10 at 11 39 01 PM](https://user-images.githubusercontent.com/151481/92778852-2b5c6500-f3bf-11ea-842d-f3bf748e6522.jpg)

2020-09-11 05:18 UTC, DigneshGujarathi commented on src/components/UI/SearchDialogBox/SearchDialogBox.tsx
>            <AutoComplete
Is there any reason we're using material autocomplete instead of the AutoComplete component?

2020-09-14 11:52 UTC, DigneshGujarathi reviewed
Looks good

2020-09-14 16:47 UTC, kurund approved these changes

2020-09-14 16:47 UTC, merged