API details from current window.location
glific/glific-frontend pull request #533
Opened 2020-09-24 16:01 UTC by rathorevaibhav

## Summary

API details to be based on current frontend url

## Test Plan

Not needed

2020-09-24 17:10 UTC, rathorevaibhav commented
@kurund @DigneshGujarathi I have a doubt on the `config/index.ts` file as it contains most of the things that are there in `common/constants.ts`. Let's discuss if there's scope for cleanup

2020-09-24 18:51 UTC, kurund requested changes
@rathorevaibhav Let's move all the URL related to config or add urls.ts and move all to that file.

Functionality is working as expected. Tested http and ws requests

2020-09-25 11:03 UTC, rathorevaibhav commented
@kurund ready for review again

2020-09-25 11:49 UTC, Satendra-SR commented on Dockerfile
> +ENV REACT_APP_GLIFIC_API_PORT $REACT_APP_GLIFIC_API_PORT
👍

2020-09-25 11:51 UTC, Satendra-SR commented on README.md
> +--build-arg REACT_APP_GLIFIC_API_PORT=API-PORT \
Thanks for updating the readme as well 👍

2020-09-25 12:17 UTC, kurund approved these changes
Looks good!

2020-09-25 12:17 UTC, merged