ooltip added on media
glific/glific-frontend pull request #770
Opened 2020-12-01 04:52 UTC by rathorevaibhav

## Summary

Fixes for #749

2020-12-01 18:11 UTC, kurund requested changes

2020-12-01 18:11 UTC, kurund commented on src/components/UI/Layout/Navigation/SideDrawer/SideDrawer.tsx
> +                  <span>
@rathorevaibhav SPAN is an inline element. This may work, but may not be the best practice.

2020-12-02 12:09 UTC, rathorevaibhav commented
@kurund ready for review again

2020-12-03 03:20 UTC, kurund approved these changes
Looks good!

2020-12-03 03:20 UTC, merged